name: Backend

on:
  push:
    paths:
      - "backend/**"
      - ".github/workflows/backend-CI.yml"
  pull_request:
    paths:
      - "backend/**"

jobs:
  build-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"
          cache-dependency-path: "backend/package-lock.json"

      - name: Install deps
        run: npm ci

      - name: Build
        run: npm run build --if-present

      - name: Test (with coverage)
        run: |
          npm test -- --coverage || true

      - name: List coverage files (debug)
        if: always()
        run: |
          echo "Looking for lcov.info under backend/coverage/"
          ls -R coverage || true

      - name: Coverage summary (Job Summary)
        if: ${{ hashFiles('backend/coverage/**/lcov.info') != '' }}
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: "backend/coverage/**/lcov.info"
          badge: true
          format: "markdown"
          thresholds: "60 80"

      - name: Better Test Reports (PR comment & artifact)
        if: ${{ hashFiles('backend/coverage/**/lcov.info') != '' }}
        uses: mridang/action-test-reporter@v1.3.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          working-directory: backend
          coverage-file: backend/coverage/**/lcov.info
          upload-coverage-report: true

      - name: Upload coverage
        uses: actions/upload-artifact@v4
        with:
          name: backend-coverage
          path: backend/coverage
          if-no-files-found: ignore

      - name: Upload build
        uses: actions/upload-artifact@v4
        with:
          name: backend-build
          path: |
            backend/dist
            backend/build
          if-no-files-found: ignore
