name: Backend

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: frontend   # 👈 alle run-commando’s uitvoeren in ./frontend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json  # 👈 correcte cache-path

      - name: Install dependencies
        run: npm ci

      - name: Build the code
        run: npx ng build --configuration production

      - name: Test the code (unit tests + coverage)
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb
          xvfb-run -a npx ng test --watch=false --code-coverage --browsers=ChromeHeadless

      - name: Generate coverage summary
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: frontend/coverage/**/lcov.info  # 👈 let op het pad
          badge: true
          fail_below_min: false
          format: markdown
          hide_complexity: true
          output: both
          thresholds: '60 80'

      - name: Upload coverage HTML
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: frontend/coverage/**
