name: Frontend

on:
  push:
    paths:
      - "frontend/**"
      - ".github/workflows/frontend-CI.yml"
  pull_request:
    paths:
      - "frontend/**"

jobs:
  build-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node (Angular 12 ↔ Node 18)
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"
          cache-dependency-path: "frontend/package-lock.json"

      - name: Install deps
        run: npm ci

      # Chrome voor Karma ChromeHeadless
      - name: Setup Chrome
        id: chrome
        uses: browser-actions/setup-chrome@v1

      - name: Build (Angular)
        run: npx ng build --configuration production

      - name: Test (with coverage)
        env:
          CHROME_BIN: ${{ steps.chrome.outputs.chrome-path }}
        run: |
          npm test -- --watch=false --browsers=ChromeHeadless --code-coverage || true

      # Toon eventueel de coverage-structuur in de logs (handig bij debuggen)
      - name: List coverage files (debug)
        if: always()
        run: |
          echo "Looking for lcov.info under frontend/coverage/"
          ls -R coverage || true

      - name: Coverage summary (Job Summary)
        if: ${{ hashFiles('frontend/coverage/**/lcov.info') != '' }}
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: "frontend/coverage/**/lcov.info"
          badge: true
          format: "markdown"
          thresholds: "60 80"

      - name: Better Test Reports (PR comment & artifact)
        if: ${{ hashFiles('frontend/coverage/**/lcov.info') != '' }}
        uses: mridang/action-test-reporter@v1.3.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          working-directory: frontend
          coverage-file: frontend/coverage/**/lcov.info
          upload-coverage-report: true

      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: frontend-coverage
          path: frontend/coverage
          if-no-files-found: ignore

      - name: Upload production build
        uses: actions/upload-artifact@v4
        with:
          name: frontend-dist
          path: frontend/dist
          if-no-files-found: warn
