name: Backend

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    # Alle npm/ng commands in de frontend-map
    defaults:
      run:
        working-directory: frontend

    steps:
      # 1) Checkout
      - name: Checkout
        uses: actions/checkout@v4

      # 2) Node/NPM
      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      # 3) Dependencies
      - name: Install dependencies
        run: npm ci

      # 4) Build
      - name: Build the code
        run: npx ng build --configuration production

      # 5) Tests + coverage (laat de job doorgaan ook als tests falen)
      - name: Test the code (unit tests + coverage)
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb
          # CI-vriendelijke Chrome wrapper (no sandbox)
          cat << 'SH' > /tmp/chrome-no-sandbox.sh
          #!/usr/bin/env bash
          BIN="$(command -v google-chrome || command -v google-chrome-stable || command -v chromium || command -v chromium-browser)"
          exec "$BIN" --no-sandbox --disable-setuid-sandbox --disable-gpu --disable-dev-shm-usage "$@"
          SH
          chmod +x /tmp/chrome-no-sandbox.sh
          export CHROME_BIN=/tmp/chrome-no-sandbox.sh

          xvfb-run -a npx ng test --watch=false --code-coverage --browsers=ChromeHeadless || true
        continue-on-error: true

      # 6) Normaliseer het pad naar één bestand (de action verwacht geen glob)
      - name: Locate/normalize lcov path
        if: always()
        run: |
          mkdir -p frontend/coverage
          # Zoek een lcov.info (Angular zet die typisch in coverage/<project>/lcov.info)
          FOUND=$(ls -1 frontend/coverage/*/lcov.info 2>/dev/null | head -n 1 || true)
          if [ -n "$FOUND" ]; then
            cp "$FOUND" frontend/coverage/lcov.info
            echo "Using $FOUND -> frontend/coverage/lcov.info"
          elif [ -f frontend/coverage/lcov.info ]; then
            echo "Using existing frontend/coverage/lcov.info"
          else
            # fallback dummy zodat de reporter nooit crasht
            echo -e "TN:\nSF:dummy.ts\nDA:1,0\nLF:1\nLH:0\nend_of_record" > frontend/coverage/lcov.info
            echo "Created dummy frontend/coverage/lcov.info"
          fi

      # 7) Better Test Reports Action (v1.3.0) — verschijnt in de Run Summary
      - name: Better Test Reports Action
        if: always()
        uses: mridang/action-test-reporter@v1.3.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          working-directory: frontend
          coverage-file: frontend/coverage/lcov.info
          upload-coverage-report: true

      # 8) (optioneel) HTML coverage uploaden (als aanwezig)
      - name: Upload coverage HTML
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: frontend/coverage/**
          if-no-files-found: ignore
