name: Backend

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    # Voer alle npm/ng commando's uit in de frontend-map
    defaults:
      run:
        working-directory: frontend

    steps:
      # 1) Checkout
      - name: Checkout
        uses: actions/checkout@v4

      # 2) Node/NPM (cache op lockfile)
      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      # 3) Dependencies
      - name: Install dependencies
        run: npm ci

      # 4) Build
      - name: Build the code
        run: npx ng build --configuration production

      # 5) Tests + coverage (laten doorlopen ook als er failures zijn)
      - name: Test the code (unit tests + coverage)
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb
          xvfb-run -a npx ng test --watch=false --code-coverage --browsers=ChromeHeadless || true
        continue-on-error: true

      # 6) Coverage-samenvatting in de run (altijd uitvoeren)
      - name: Generate coverage summary
        if: always()
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: frontend/coverage/**/lcov.info
          badge: true
          fail_below_min: false
          format: markdown
          hide_complexity: true
          output: both
          thresholds: '60 80'

      # 7) Volledige HTML coverage als artifact (altijd uploaden)
      - name: Upload coverage HTML
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: frontend/coverage/**
